version: "3.8"
services:
  patient:
    image: patient
    ports:
      - "8081:8081"

  database:
    image: "postgres"
    hostname: postgres
    env_file:
      - database.env
    volumes:
      -database-data: /var/lib/postgresql/data/

volumes:
  database-data:

networks:
  patient-network: